# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.1.1
_src_path: git@github.com:milo-minderbinder/copier-bash-getopts.git
description: pyenv-upgrade is a CLI utility to update Python versions installed with
    pyenv.
extra_functions:
- contains_value
file_name: pyenv-upgrade.bash
function_name: main
include_common_functions: true
include_header: true
include_usage: true
max_positional_args: 1
min_positional_args: -1
opts: []
positional_args_help:
- <VERSION_PREFIX> (optional) Python version prefix to check (e.g. 3, 3.12)
positional_args_metavars: '[<VERSION_PREFIX>]'
project_name: pyenv-upgrade
project_slug: pyenv-upgrade
short_description: CLI utility to update Python versions installed with pyenv.
switches:
-   additive: true
    description: increase verbosity
    dest: verbosity
    flag: v
-   additive: false
    description: list matching versions and exit without installing
    dest: list
    flag: l


